import json


class ResponseParser:
    """
    Parses the final structured response produced by Talk-to-AI.

    Expected input:

    {
        "answers": {
            "question_id": "answer"
        }
    }

    Output:

    {
        "question_id": "clean answer"
    }

    This class does NOT:
    - call Gemini
    - manage the conversation
    - generate questions
    - normalize the final report
    """

    BLOCKED_FIELD_KEYWORDS = {
        "password",
        "passcode",
        "pin",
        "pattern",
        "otp",
        "secret",
        "login_credential",
    }

    def __init__(self, questions=None):
        """
        questions:
            Questions generated by the existing Question Engine.

        They are used to make sure Gemini only returns
        valid question IDs.
        """
        self.questions = questions or []

    # =========================================================
    # Question ID handling
    # =========================================================

    @staticmethod
    def _get_question_id(question):
        """Get question ID from either a dictionary or Question object."""

        if isinstance(question, dict):
            return question.get("id")

        return getattr(question, "id", None)

    def _get_valid_question_ids(self):
        """Return the IDs belonging to the current question set."""

        valid_ids = set()

        for question in self.questions:
            question_id = self._get_question_id(question)

            if question_id:
                valid_ids.add(str(question_id))

        return valid_ids

    # =========================================================
    # Sensitive-field protection
    # =========================================================

    @classmethod
    def _is_blocked_field(cls, question_id):
        """Check whether a field contains sensitive credential information."""

        question_id = str(question_id).strip().lower()

        return any(
            keyword in question_id
            for keyword in cls.BLOCKED_FIELD_KEYWORDS
        )

    # =========================================================
    # Input parsing
    # =========================================================

    @staticmethod
    def _parse_json(response):
        """
        Convert Gemini's response into a Python dictionary.

        Accepts:
        - dictionary
        - JSON string
        """

        if isinstance(response, dict):
            return response

        if not isinstance(response, str):
            raise ValueError("Talk-to-AI response must be a dictionary or JSON string.")

        response = response.strip()

        if not response:
            raise ValueError("Talk-to-AI response is empty.")

        try:
            return json.loads(response)

        except json.JSONDecodeError as exc:
            raise ValueError(
                "Talk-to-AI response contains invalid JSON."
            ) from exc

    # =========================================================
    # Answer validation
    # =========================================================

    def _validate_answers(self, answers):
        """
        Validate the answers object and keep only valid,
        user-provided answer values.
        """

        if not isinstance(answers, dict):
            raise ValueError("'answers' must be a JSON object.")

        valid_question_ids = self._get_valid_question_ids()

        cleaned_answers = {}

        for question_id, answer in answers.items():

            if not isinstance(question_id, str):
                continue

            question_id = question_id.strip()

            if not question_id:
                continue

            # Never accept sensitive credential fields.
            if self._is_blocked_field(question_id):
                continue

            # If a question set is available, reject unknown IDs.
            if valid_question_ids and question_id not in valid_question_ids:
                continue

            # Never store null answers.
            if answer is None:
                continue

            # Clean string answers.
            if isinstance(answer, str):
                answer = answer.strip()

                if not answer:
                    continue

            cleaned_answers[question_id] = answer

        return cleaned_answers

    # =========================================================
    # Public parser
    # =========================================================

    def parse(self, response):
        """
        Parse and validate the final Talk-to-AI response.

        Returns:

        {
            "success": True,
            "answers": {
                ...
            }
        }

        or:

        {
            "success": False,
            "error": "..."
        }
        """

        try:
            data = self._parse_json(response)

            if not isinstance(data, dict):
                return {
                    "success": False,
                    "error": "Talk-to-AI response must be a JSON object."
                }

            if "answers" not in data:
                return {
                    "success": False,
                    "error": "Talk-to-AI response is missing the 'answers' field."
                }

            cleaned_answers = self._validate_answers(
                data["answers"]
            )

            return {
                "success": True,
                "answers": cleaned_answers
            }

        except ValueError as exc:
            return {
                "success": False,
                "error": str(exc)
            }

        except Exception as exc:
            return {
                "success": False,
                "error": "Unexpected error while parsing Talk-to-AI response.",
                "details": str(exc)
            }